### ISSUE TITLE
Add an ability to build / deploy mobile applications in one command

### ISSUE THREAD

**Issue by Nyarum** [raphaeljlps/berg#5]
We need a command like `berg build (android / ios)`

Dependency:
- Every team / company has a CI for build / deploy code.
- Setting your android / ios builds via fastlane or an another tool
- And separate it to two branches with names like `ios_builds` and `android_builds` where you'll have a CI config with preconfigured commands for build / deploy.

While it uses a github with slack for notification we can to do next things:
- [x] When any human will use `berg build (android / ios)` then the Berg will use self-power for merge a base branch in a preconfigured branch for build & deploy.

**Comment by Nyarum** [comment]
Test https://github.com/raphaeljlps/berg/commit/8c692e554f4b4cc40784d891b39308190023f51e

**Comment by Nyarum** [comment]
Related commits - https://github.com/raphaeljlps/berg/commit/8c692e554f4b4cc40784d891b39308190023f51e, https://github.com/raphaeljlps/berg/commit/0c7cfb5b4b27b836b3a7d8156467b49bf3352ff1, https://github.com/raphaeljlps/berg/commit/96ea591d01b85ff45b707a1f1b0dc32d27b877b0, https://github.com/raphaeljlps/berg/commit/700924c747d12b8e911f866a4cd114db7f10776f

**Comment by raphaeljlps** [comment]
Let me take a look mister @Nyarum

**Comment by raphaeljlps** [comment]
PR merged

**Comment by Nyarum** [comment]
Done
